# Generated by Django 5.0.1 on 2024-02-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_admins', '0005_branche_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.CharField(max_length=100)),
                ('layout', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_type', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=100)),
                ('nub_seats', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_admins.agency')),
                ('bus_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.bus_layout')),
            ],
        ),
    ]
