# Generated by Django 5.0.1 on 2024-02-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='nub_seats',
            new_name='numb_seats',
        ),
    ]
