# Generated by Django 5.0.1 on 2024-02-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_rename_nub_seats_bus_numb_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='buy_type',
            new_name='bus_type',
        ),
    ]
