# Generated by Django 5.0.1 on 2024-02-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_rename_buy_type_bus_bus_type'),
        ('sub_admins', '0005_branche_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_origin', models.CharField(max_length=150)),
                ('to_destination', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('trip_cost', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=20)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_admins.agency')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_admins.branche')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencies.bus')),
            ],
        ),
    ]
