# Generated by Django 5.0.1 on 2024-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_driver_trip_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
