# Generated by Django 5.0.1 on 2024-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_reservation_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
