# Generated by Django 5.0.1 on 2024-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_num', models.CharField(max_length=100)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
