# Generated by Django 5.0.1 on 2024-02-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admins', '0002_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_admins.agency'),
        ),
    ]
