# Generated by Django 5.0.1 on 2024-02-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admins', '0004_rename_agency_id_user_agency_branche_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branche',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
