# Generated by Django 5.0.1 on 2024-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admins', '0006_alter_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
